### ISSUE TITLE
m2crypto is a pain

### ISSUE THREAD

**Issue by ahnitz** [ligo-cbc/pycbc-glue#2]
Glue requires m2cypto. At the moment this is an undeclared depency. Is there a way we can get rid of it? What critical packages need it? 

If one wants to install m2crypto it has to be as follows.

       env SWIG_FEATURES="-cpperraswarn -includeall -I/usr/include/openssl" pip install M2Crypto

**Comment by duncan-brown** [comment]
It's the tool needed to connect to X509 authenticated web services (segment database and ligo data find servers running under apache):

proxy = M2Crypto.X509.load_cert(path)

Probably best to declare the dependency.

**Comment by ahnitz** [comment]
Ok, I guess the real issue is that our ssl versions are too old. Maybe that will go away in the next os upgrade.

**Comment by ahnitz** [comment]
For future reference the error if one tries to do a normal install of M2Crypto is

```
    /usr/include/openssl/opensslconf.h:31: Error: CPP #error ""This openssl-devel package does not work your architecture?"". Use the -cpperraswarn option to continue swig processing.
    error: command 'swig' failed with exit status 1
```
